print("Hello World!")
print("This will work!")
print('This will also work!')
print("Hello World!", end=" ")
print("I will print on the same line.")
print(3)
print(358)
print(50000)
print(3 + 3)
print(2 * 5)
print("I am", 35, "years old.")